import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Image Gallery',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <main className='max-w-6xl mx-auto'>
        {children}
      </main>
    </html>
  )
}
